### PR TITLE
Added WEP Support

### PR DESCRIPTION
**Pull request by timschumi**
- Key checking is a bit messy, but I don't know how I could clean it up further.

### CODE REVIEW

**Comment by timschumi** [comment]
@mh4x0f May you be able to help with this? I have no Idea what's causing this

**Comment by mh4x0f** [comment]
> Clients can not connect with non-hexadecimal keys (I don't know where the Error is)

I think that this problem come from the hostapd, I'll check on the code in hostapd coming soon.

**Comment by timschumi** [comment]
@mh4x0f This should now fix WEP. I could not find any remaining Errors, but I did not test every single combination of the settings.

**Comment by mh4x0f** [comment]
nice work brown thank's...

**Pull request merged**
