### PR TITLE
Added Key checking

### PR DESCRIPTION
**Pull request by timschumi**
This does not prevent the user from starting the AP with a bad key, it does only show if the key is compatible or not

### CODE REVIEW

**Comment by mh4x0f** [comment]
nice idea, change the border style for 1px. I don't use border more than 1px.

**Comment by timschumi** [comment]
Ok, now changed the border size. I'll probably add a Warning Message in another PR if the user tries to start the AP anyways

**Comment by mh4x0f** [comment]
add on these same PR.

**Comment by timschumi** [comment]
I just killed off my patching branch, I will open a new PR

**Comment by mh4x0f** [comment]
lol

**Comment by timschumi** [comment]
I nearly deleted my fork of the program

EDIT: I deleted it, but luckily I had another version of my Repository in the Bin.

**Pull request closed without merging**
