### PR TITLE
Correct cleanup when uninstalling the .deb file

### PR DESCRIPTION
**Pull request by timschumi**
Automatically removing *.pyc files when uninstalling the .deb file.

But there are still some files remaining in templates/Update. Why are they being created? Shouldn't they be in the repository all the time?

### CODE REVIEW

**Comment by mh4x0f** [comment]
all the file .pyc are created when a .py file is imported. they be in the repository because they are generated when run program(imported)  and the files .pyc just is machine code which is what runs the fastest

**Comment by timschumi** [comment]
No, I didn't meant the .pyc files when I asked why there are some files remaining. There are some pictures remaining which seem to be left over by the Java Phishing Module.

The real purpose of this PR is that the symlink to the program (or the link of the program inside update-alternatives) are removed together with the *.pyc files, which are created at run time. So if this is merged, the /usr/share/WiFi-Pumpkin folder will be cleaned up at uninstallation time. The folder will get deleted completely, as long as the user didn't save any files inside it manually.

**Comment by timschumi** [comment]
I forgot to mention that I only changed this for the DEB files

**Comment by mh4x0f** [comment]
@TimSchumi all the files in templates/Update, are unzipped on startup the tool and they be not  in the repository because is not necessary. I don't change anything.

**Comment by timschumi** [comment]
@mh4x0f Just wanted to ask where they are from

**Comment by mh4x0f** [comment]
@TimSchumi they are from **/settings/source.tar.gz**

**Pull request merged**
